a, b, c = input().split()
a = int(a)
b = int(b)
c = int(c)
print((a+b)%c)
print((a%c + b%c)%c)
print((a*b)%c)
print((a%c * b%c)%c)

#  def fir(a,b,c):
#     print((a+b)%c)
#     print((a%c)+(b%c)%c)
#     print((a*b)%c)
#     print(((a%c)*(b%c))%c)

# A, B, C= input().split()
# A= int(A)
# B= int(B)
# C= int(C)
# fir(A,B,C)